set fallback

compile:
  mkdir -p build
  riscv64-unknown-linux-gnu-gcc -O2 -march=rv32e_zicsr -nostdlib -L -Ttext -mabi=ilp32e char-test.c -o build/char-test.elf
  riscv64-unknown-linux-gnu-objdump -d build/char-test.elf > build/char-test.txt
  riscv64-unknown-linux-gnu-objcopy -O binary build/char-test.elf build/char-test.bin

clean:
  rm -rf ./build
