[TaoHe]
'Total Cycle' = 20613492
'area(um^2)' = 30682.400000000001
commit = '0d97cbc3'
'freq(MHz)' = 395.78399999999999
message = '''[taohe] refactor IFU & ICache then axi4 request directly from ICache

Befor: IFU -> ICache
        |-> Memory

After: IFU -> ICache -> Memory'''
time = '2025-12-31 19:17:51'

    [TaoHe.'AXI Arbiter']
    ifuAXIWaitingCycleCounter = 7870280
    ifuArbiterWaitingCycleCounter = 0
    lsuAXILoadWaitingCycleCounter = 8726194
    lsuAXIStoreWaitingCycleCounter = 8719320
    lsuArbiterLoadWaitingCycleCounter = 0
    lsuArbiterStoreWaitingCycleCounter = 0

    [TaoHe.EXU]
    arithmeticDoneCounter = 382789

    [TaoHe.IDU.'Arithmetic Inst']
    'Average Cycle per Inst' = 14.60502268845265
    'Cycle Count' = 5378285
    'Cycle Percentage' = 26.091091213463493
    'Inst Count' = 368249
    'Inst Percentage' = 47.779744187917302

    [TaoHe.IDU.'Branch Inst']
    'Average Cycle per Inst' = 9.168558657849621
    'Cycle Count' = 1497409
    'Cycle Percentage' = 7.2642180179855025
    'Inst Count' = 163320
    'Inst Percentage' = 21.190520057815917

    [TaoHe.IDU.'Jump Inst']
    'Average Cycle per Inst' = 33.618365120565777
    'Cycle Count' = 893677
    'Cycle Percentage' = 4.3353983885893763
    'Inst Count' = 26583
    'Inst Percentage' = 3.4491035678234172

    [TaoHe.IDU.'Load Inst']
    'Average Cycle per Inst' = 78.844262547786414
    'Cycle Count' = 10229570
    'Cycle Percentage' = 49.625604434222012
    'Inst Count' = 129744
    'Inst Percentage' = 16.834085441962213

    [TaoHe.IDU.'Store Inst']
    'Average Cycle per Inst' = 32.865872946138303
    'Cycle Count' = 2244279
    'Cycle Percentage' = 10.887427515920155
    'Inst Count' = 68286
    'Inst Percentage' = 8.8600039962528641

    [TaoHe.IFU]
    fetchInstNumCounter = 770722
    fetchWaitingCycleCounter = 8476718
    iCacheHitCounter = 467504

    [TaoHe.LSU]
    loadDataValidCounter = 129698
    loadWaitingCycleCounter = 8726194
    storeWaitingCycleCounter = 8719320
